spring.datasource.url=jdbc:sqlite:dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jackson.deserialization.UNWRAP_ROOT_VALUE=true

image.default=https://static.productionready.io/images/smiley-cyrus.jpg

jwt.secret=nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
jwt.sessionTime=86400

mybatis.configuration.cache-enabled=true
mybatis.configuration.default-statement-timeout=3000
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.type-handlers-package=io.spring.infrastructure.mybatis
mybatis.mapper-locations=mapper/*.xml

logging.level.io.spring.infrastructure.mybatis.readservice.ArticleReadService=DEBUG
logging.level.io.spring.infrastructure.mybatis.mapper=DEBUG

platform.baseline.java-version=11
platform.baseline.spring-boot-version=2.6.3
platform.dependencies[0].name=Spring Boot
platform.dependencies[0].from=2.6.3
platform.dependencies[0].to=3.3.13
platform.dependencies[1].name=Spring Framework
platform.dependencies[1].from=5.3.15
platform.dependencies[1].to=6.1.21
platform.dependencies[2].name=Java
platform.dependencies[2].from=11
platform.dependencies[2].to=17
platform.dependencies[3].name=Netflix DGS
platform.dependencies[3].from=4.9.21
platform.dependencies[3].to=8.7.1
platform.dependencies[4].name=MyBatis Spring Boot
platform.dependencies[4].from=2.2.2
platform.dependencies[4].to=3.0.4
platform.dependencies[5].name=jjwt
platform.dependencies[5].from=0.11.2
platform.dependencies[5].to=0.12.6
platform.dependencies[6].name=sqlite-jdbc
platform.dependencies[6].from=3.36.0.3
platform.dependencies[6].to=3.49.1.0
platform.dependencies[7].name=REST Assured (test)
platform.dependencies[7].from=4.5.1
platform.dependencies[7].to=5.5.2
platform.dependencies[8].name=Servlet / Validation API
platform.dependencies[8].from=javax
platform.dependencies[8].to=jakarta
